---
# tasks file for gameoflife
    - fail: 
        msg: "this playbook is only designed "
      when: 
      - ansible_os_family != "Debian"
    - name: " format hdfs "
      command:
        argv:
          - hdfs namenode -format
          - sh /opt/hadoop/sbin/start-dfs.sh
          - sh /opt/hadoop/sbin/start-yarn.sh
          - sh /opt/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver
